---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  verbs:
  - get
  - patch
- apiGroups:
  - krotos.warewave.io
  resources:
  - databasecredentialrotations
  - vaultconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - krotos.warewave.io
  resources:
  - databasecredentialrotations/finalizers
  - vaultconnections/finalizers
  verbs:
  - update
- apiGroups:
  - krotos.warewave.io
  resources:
  - databasecredentialrotations/status
  - vaultconnections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - secrets.hashicorp.com
  resources:
  - vaultstaticsecrets
  verbs:
  - get
  - patch
