apiVersion: krotos.warewave.io/v1alpha1
kind: DatabaseCredentialRotation
metadata:
  labels:
    app.kubernetes.io/name: krotos
    app.kubernetes.io/managed-by: kustomize
  name: orders-db-app-user
spec:
  engine: postgresql
  database:
    host: orders-pg.db.svc
    port: 5432
    database: orders
    tls:
      mode: require
  masterCredentials:
    vault:
      connectionRef: main-vault
      mount: secret
      path: db/orders/master
  target:
    username: orders_app
    vault:
      connectionRef: main-vault
      mount: secret
      path: apps/orders/db
      passwordKey: password
  schedule:
    every: 30d
  window:
    timezone: Europe/Istanbul
    days: [Sat, Sun]
    start: "02:00"
    duration: 3h
  secretSync:
    type: None
  restartTargets:
  - kind: Deployment
    name: orders-api
