//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseSettings) DeepCopyInto(out *ClickHouseSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseSettings.
func (in *ClickHouseSettings) DeepCopy() *ClickHouseSettings {
	if in == nil {
		return nil
	}
	out := new(ClickHouseSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseCredentialRotation) DeepCopyInto(out *DatabaseCredentialRotation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseCredentialRotation.
func (in *DatabaseCredentialRotation) DeepCopy() *DatabaseCredentialRotation {
	if in == nil {
		return nil
	}
	out := new(DatabaseCredentialRotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseCredentialRotation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseCredentialRotationList) DeepCopyInto(out *DatabaseCredentialRotationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabaseCredentialRotation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseCredentialRotationList.
func (in *DatabaseCredentialRotationList) DeepCopy() *DatabaseCredentialRotationList {
	if in == nil {
		return nil
	}
	out := new(DatabaseCredentialRotationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseCredentialRotationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseCredentialRotationSpec) DeepCopyInto(out *DatabaseCredentialRotationSpec) {
	*out = *in
	in.Database.DeepCopyInto(&out.Database)
	in.MasterCredentials.DeepCopyInto(&out.MasterCredentials)
	in.Target.DeepCopyInto(&out.Target)
	out.PasswordPolicy = in.PasswordPolicy
	out.Schedule = in.Schedule
	in.Window.DeepCopyInto(&out.Window)
	in.SecretSync.DeepCopyInto(&out.SecretSync)
	if in.RestartTargets != nil {
		in, out := &in.RestartTargets, &out.RestartTargets
		*out = make([]RestartTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.RolloutTimeout = in.RolloutTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseCredentialRotationSpec.
func (in *DatabaseCredentialRotationSpec) DeepCopy() *DatabaseCredentialRotationSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseCredentialRotationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseCredentialRotationStatus) DeepCopyInto(out *DatabaseCredentialRotationStatus) {
	*out = *in
	if in.LastRotationTime != nil {
		in, out := &in.LastRotationTime, &out.LastRotationTime
		*out = (*in).DeepCopy()
	}
	if in.SecretSyncStartTime != nil {
		in, out := &in.SecretSyncStartTime, &out.SecretSyncStartTime
		*out = (*in).DeepCopy()
	}
	if in.RolloutStartTime != nil {
		in, out := &in.RolloutStartTime, &out.RolloutStartTime
		*out = (*in).DeepCopy()
	}
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
	if in.NextScheduledTime != nil {
		in, out := &in.NextScheduledTime, &out.NextScheduledTime
		*out = (*in).DeepCopy()
	}
	if in.NextWindowStart != nil {
		in, out := &in.NextWindowStart, &out.NextWindowStart
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseCredentialRotationStatus.
func (in *DatabaseCredentialRotationStatus) DeepCopy() *DatabaseCredentialRotationStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseCredentialRotationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseEndpoint) DeepCopyInto(out *DatabaseEndpoint) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(DatabaseTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.ClickHouse != nil {
		in, out := &in.ClickHouse, &out.ClickHouse
		*out = new(ClickHouseSettings)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseEndpoint.
func (in *DatabaseEndpoint) DeepCopy() *DatabaseEndpoint {
	if in == nil {
		return nil
	}
	out := new(DatabaseEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseTLS) DeepCopyInto(out *DatabaseTLS) {
	*out = *in
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseTLS.
func (in *DatabaseTLS) DeepCopy() *DatabaseTLS {
	if in == nil {
		return nil
	}
	out := new(DatabaseTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindow) DeepCopyInto(out *MaintenanceWindow) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]Weekday, len(*in))
		copy(*out, *in)
	}
	out.Duration = in.Duration
	out.MinRemaining = in.MinRemaining
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindow.
func (in *MaintenanceWindow) DeepCopy() *MaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterCredentials) DeepCopyInto(out *MasterCredentials) {
	*out = *in
	if in.Vault != nil {
		in, out := &in.Vault, &out.Vault
		*out = new(VaultCredentialsReference)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretCredentialsReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterCredentials.
func (in *MasterCredentials) DeepCopy() *MasterCredentials {
	if in == nil {
		return nil
	}
	out := new(MasterCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordPolicy) DeepCopyInto(out *PasswordPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordPolicy.
func (in *PasswordPolicy) DeepCopy() *PasswordPolicy {
	if in == nil {
		return nil
	}
	out := new(PasswordPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartTarget) DeepCopyInto(out *RestartTarget) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartTarget.
func (in *RestartTarget) DeepCopy() *RestartTarget {
	if in == nil {
		return nil
	}
	out := new(RestartTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationTarget) DeepCopyInto(out *RotationTarget) {
	*out = *in
	if in.MySQLHost != nil {
		in, out := &in.MySQLHost, &out.MySQLHost
		*out = new(string)
		**out = **in
	}
	out.Vault = in.Vault
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationTarget.
func (in *RotationTarget) DeepCopy() *RotationTarget {
	if in == nil {
		return nil
	}
	out := new(RotationTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Schedule) DeepCopyInto(out *Schedule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Schedule.
func (in *Schedule) DeepCopy() *Schedule {
	if in == nil {
		return nil
	}
	out := new(Schedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCredentialsReference) DeepCopyInto(out *SecretCredentialsReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCredentialsReference.
func (in *SecretCredentialsReference) DeepCopy() *SecretCredentialsReference {
	if in == nil {
		return nil
	}
	out := new(SecretCredentialsReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSync) DeepCopyInto(out *SecretSync) {
	*out = *in
	if in.ExternalSecret != nil {
		in, out := &in.ExternalSecret, &out.ExternalSecret
		*out = new(SyncedSecretReference)
		**out = **in
	}
	if in.VaultStaticSecret != nil {
		in, out := &in.VaultStaticSecret, &out.VaultStaticSecret
		*out = new(SyncedSecretReference)
		**out = **in
	}
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSync.
func (in *SecretSync) DeepCopy() *SecretSync {
	if in == nil {
		return nil
	}
	out := new(SecretSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncedSecretReference) DeepCopyInto(out *SyncedSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncedSecretReference.
func (in *SyncedSecretReference) DeepCopy() *SyncedSecretReference {
	if in == nil {
		return nil
	}
	out := new(SyncedSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAuth) DeepCopyInto(out *VaultAuth) {
	*out = *in
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(VaultKubernetesAuth)
		**out = **in
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(VaultTokenAuth)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAuth.
func (in *VaultAuth) DeepCopy() *VaultAuth {
	if in == nil {
		return nil
	}
	out := new(VaultAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultConnection) DeepCopyInto(out *VaultConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultConnection.
func (in *VaultConnection) DeepCopy() *VaultConnection {
	if in == nil {
		return nil
	}
	out := new(VaultConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultConnectionList) DeepCopyInto(out *VaultConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultConnectionList.
func (in *VaultConnectionList) DeepCopy() *VaultConnectionList {
	if in == nil {
		return nil
	}
	out := new(VaultConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultConnectionSpec) DeepCopyInto(out *VaultConnectionSpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(VaultTLS)
		(*in).DeepCopyInto(*out)
	}
	in.Auth.DeepCopyInto(&out.Auth)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultConnectionSpec.
func (in *VaultConnectionSpec) DeepCopy() *VaultConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(VaultConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultConnectionStatus) DeepCopyInto(out *VaultConnectionStatus) {
	*out = *in
	if in.LastCheckedTime != nil {
		in, out := &in.LastCheckedTime, &out.LastCheckedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultConnectionStatus.
func (in *VaultConnectionStatus) DeepCopy() *VaultConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(VaultConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCredentialsReference) DeepCopyInto(out *VaultCredentialsReference) {
	*out = *in
	out.VaultSecretReference = in.VaultSecretReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCredentialsReference.
func (in *VaultCredentialsReference) DeepCopy() *VaultCredentialsReference {
	if in == nil {
		return nil
	}
	out := new(VaultCredentialsReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKubernetesAuth) DeepCopyInto(out *VaultKubernetesAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKubernetesAuth.
func (in *VaultKubernetesAuth) DeepCopy() *VaultKubernetesAuth {
	if in == nil {
		return nil
	}
	out := new(VaultKubernetesAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSecretReference) DeepCopyInto(out *VaultSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSecretReference.
func (in *VaultSecretReference) DeepCopy() *VaultSecretReference {
	if in == nil {
		return nil
	}
	out := new(VaultSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTLS) DeepCopyInto(out *VaultTLS) {
	*out = *in
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTLS.
func (in *VaultTLS) DeepCopy() *VaultTLS {
	if in == nil {
		return nil
	}
	out := new(VaultTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTargetReference) DeepCopyInto(out *VaultTargetReference) {
	*out = *in
	out.VaultSecretReference = in.VaultSecretReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTargetReference.
func (in *VaultTargetReference) DeepCopy() *VaultTargetReference {
	if in == nil {
		return nil
	}
	out := new(VaultTargetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTokenAuth) DeepCopyInto(out *VaultTokenAuth) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTokenAuth.
func (in *VaultTokenAuth) DeepCopy() *VaultTokenAuth {
	if in == nil {
		return nil
	}
	out := new(VaultTokenAuth)
	in.DeepCopyInto(out)
	return out
}
